package com.airiea.entity.model.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "entities")
public class EntityDAO {
    @DynamoDBHashKey(attributeName = "entity_id")
    @JsonProperty("entity_id")
    String entityId;

    @DynamoDBRangeKey(attributeName = "agent_name")
    @JsonProperty("agent_name")
    String agentName;

    @DynamoDBAttribute(attributeName = "task_count")
    @JsonProperty("task_count")
    Integer taskCount;

    @DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @JsonProperty("created_date")
    Date createdDate;

    @DynamoDBAttribute(attributeName = "updated_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @JsonProperty("updated_date")
    Date updatedDate;
}
